#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on utopic-juno."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='utopic')
    deployment.run_tests()
