#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on trusty-mitaka."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-mitaka',
                                           source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
