#!/usr/bin/python

"""Amulet tests on a basic neutron-api deployment on xenial-mitaka."""

from basic_deployment import NeutronAPIBasicDeployment

if __name__ == '__main__':
    deployment = NeutronAPIBasicDeployment(series='xenial')
    deployment.run_tests()
